language: ruby
script: rake spec:travis
before_script:
  - travis_retry rake spec:travis:deps
  - travis_retry rake spec:travis:sub_version
  - travis_retry rake man:build
  - travis_retry rake spec:rubygems:clone_rubygems_$RGV

branches:
  only:
    - master
    - auto
    - /.+-dev$/
    - /.+-stable$/

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: JxBi7DDJGkIF/7f/FSN/HUHpvV4EKfQccZHTPd1b2pNJn3GXo6u+tNVbAw2WjxYzPyPQI3ZcYBCU9SEXp/i7VmG8uMzh8Kyildw+miSKYKVb90uYqcsXWzbxwyNBgJLvyDkzST45H5lgnyAicee3WkFes/WDZikIajbH7ztdb04=

addons:
  code_climate:
    repo_token:
      secure: "TrzIv116JLGUxm6PAUskCYrv8KTDguncKROVwbnjVPKTGDAgoDderd8JUdDEXrKoZ9qGLD2TPYKExt9/QDl71E+qHdWnVqWv4HKCUk2P9z/VLKzHuggOUBkCXiJUhjywUieCJhI3N92bfq2EjSBbu2/OFHqWOjLQ+QCooTEBjv8="

rvm:
  - 2.4.1
  - 1.8.7

# Rubygems versions MUST be available as rake tasks
# see Rakefile:125 for the list of possible RGV values
env:
  # Test the latest rubygems release with all of our supported rubies
  - RGV=v2.6.8

matrix:
  include:
    - rvm: 2.4.1
      env: RGV=v2.6.8 BUNDLER_SPEC_SUB_VERSION=2.0.0
